# Generated by Django 3.1.7 on 2021-02-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
